name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Podman
      - name: Set up Podman
        uses: redhat-actions/setup-podman@v2
        with:
          version: latest

      # Authenticate with GitHub Container Registry
      - name: Authenticate with GitHub Container Registry
        env:
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this secret
        run: |
          echo $GHCR_TOKEN | podman login ghcr.io --username $GITHUB_ACTOR --password-stdin

      # Build the Podman container image
      - name: Build Podman image
        run: |
          podman build -t ghcr.io/${{ github.repository_owner }}/my-app:latest .

      # Push the container to GitHub Container Registry
      - name: Push Podman image to GitHub Container Registry
        run: |
          podman push ghcr.io/${{ github.repository_owner }}/my-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Deploy to Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: vercel --prod
